chatroom/urls.py
from django.conf.urls import url
from . import views
app_name = "chatroom"

urlpatterns = [
    url("^$" , views.chat_view , name = "chat_view")
]

home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"

urlpatterns = [
    url("^$" , views.homeview , name = "home"),
]

login/urls.py
from . import views
from django.conf.urls import url
app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
    url("^logout/" , views.logout , name = "logout"),
    url("^updatereset/" , views.newcr , name = "newcreds")
]

luckbuyer/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url,include

urlpatterns = [
    url("^$" , include("home.urls")),
    url("^login/" , include("login.urls")),
    url("^signup/$" , include("signup.urls")),
    url("^orders/" , include("orders.urls")),
    url("^stockmanager/" , include("stockmanager.urls")),
    url("^/chatroom" , include("chatroom.urls")),
    url('admin/', admin.site.urls),
]

orders/urls.py
from django.conf.urls import url
from . import views

app_name = "orders"

urlpatterns = [
    url("^$" , views.ordersview , name = "orders"),
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = "signup"


urlpatterns = [
    url('^$' , views.signup , name = 'signup'),
    url('^userauthentication/' , views.userauthentication , name = 'userauthentication'),
    url('^emailauthentication/' , views.emailauthentication , name = 'emailauthentication'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from signup.models import Signup as sp
from stockmanager.models import Stock as st
from chatroom.models import Chats as cht
from django.db.models import Q
# Create your views here.

def homeview(request):
    try:
        current_user = sp.objects.get(uid = request.session["uid"])
    except Exception as e:
        print(e)
        return render(request , "home/home.html")
    else:
        chats = cht.objects.filter(Q(current_user_info_id = current_user.uid)|Q(opponent_info = current_user.uid))
        all_stock = st.objects.all()
        return render(request , "home/home.html" , context = {"user_info":current_user , "all_stock":all_stock , "chats":chats})

home/templates/home/home.html
{% load static %}
{% load homefilter %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1.0">
    <meta name="keywords" content="Shopping,LuckBuyer,Luck,Buyer">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'home/home.css' %}">
    <title>LuckBuyer | Home</title>
  </head>
  <body>
    <div class="home">
      <div class="nav">
        <a href="{% url 'signup:signup' %}">signup</a>
        <a href="{% url 'login:login' %}">login</a>
        <a href="{% url 'stockmanager:stocks' %}">Stock</a>
        <a href="{% url 'orders:orders' %}">Order</a>
      </div>
      <div class="main">
          <div class="stocks">
            {% for item in all_stock %}

            {% endfor %}
          </div>
      </div>
      <div class="chat" onclick="open_chat();">
          <p>
            Chats
          </p>
      </div>
          <div class="chatArea" id="chatArea">
            <p class="closeX" onclick="close_chat();">&times;</p>
            <!-- all conversations -->
            <div class="chat-converstion">
                {% for chat in chats %}
                    {% if chat.current_user_info.uid|check_user:user_info.uid %}
                      <div class="mytext">
                        <p>
                          {{chat.current_user_info.username}}
                        </p>
                          {{chat.chat_content}}
                      </div>
                    {% else %}
                      <div class="thetext">
                        <p>
                          {{chat.opponent_info.username}}
                        </p>
                        {{chat.chat_content}}
                      </div>
                    {% endif %}
                {% endfor %}
        </div>
            <!-- end of converstions -->
            <!-- chat form -->
            <div class="submit answer">
                <form class="chatform" action="{% url 'chatroom:chat_view' %}" method="post">
                  {% csrf_token %}
                  <textarea name="textcontn" rows="3" cols="20"></textarea>
                  <input type="hidden" name="opponent_id" value="1">
                  <br>
                  <input type="submit" name="submit" value="submit">
                </form>
            </div>
          </div>
          <!-- end of chat area -->
    </div>
  </body>
  <script type="text/javascript">
    function close_chat() {
      var chat = document.getElementById('chatArea');
      chat.setAttribute("style" , "animation:animateclose .4s 1;");
    }
    function open_chat(){
      var chat = document.getElementById('chatArea');
      chat.setAttribute("style" , "display:block;animation:animatepopup .4s 1;");
    }
  </script>
</html>