home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"

urlpatterns = [
    url("^$" , views.homeview , name = "home"),
]

login/urls.py
from . import views
from django.conf.urls import url
app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
    url("^logout/" , views.logout , name = "logout"),
    url("^updatereset/" , views.newcr , name = "newcreds")
]

luckbuyer/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url,include

urlpatterns = [
    url("^$" , include("home.urls")),
    url("^login/" , include("login.urls")),
    url("^signup/$" , include("signup.urls")),
    url("^orders/" , include("orders.urls")),
    url("^stockmanager/" , include("stockmanager.urls")),
    url("^/chatroom" , include("chatroom.urls")),
    url('admin/', admin.site.urls),
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = "signup"


urlpatterns = [
    url('^$' , views.signup , name = 'signup'),
    url('^userauthentication/' , views.userauthentication , name = 'userauthentication'),
    url('^emailauthentication/' , views.emailauthentication , name = 'emailauthentication'),
]

login/models.py
from django.db import models
from signup.models import Signup as sv
# Create your models here.
class Recoverdata(models.Model):
    id = models.AutoField(primary_key = True , serialize = True)
    uid = models.ForeignKey(sv , related_name = "recnewdb" , on_delete = models.CASCADE , default = 1)
    secret_code = models.CharField(max_length = 10 , default = [*range(10)])

login/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from signup.models import Signup
import smtplib as sm ,validate_email as v,string,random
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.contrib.auth.hashers import check_password,make_password
from .models import Recoverdata

def login(request):
    if request.method == "POST":
        error_log = list()
        username = request.POST['username']
        password = request.POST['password']
        try:
            userinfo = Signup.objects.get(username = username)
            username = userinfo.username
        except Exception as e:
            error_log.append(" Wrong credentials")
            return render(request , "login/login.html" , context = {"error_log" : error_log})
        else:
            if check_password(password , userinfo.password):
                # add username to the session
                request.session["uid"] = userinfo.uid
                request.session['items'] = list()
                request.session["loginstatus"] = True

                try:
                    red_req = request.session["redirect"]
                    del request.session["redirect"]
                except Exception as e:
                    # set the sessions expiry date
                    request.session.set_expiry(0)
                    # redirect user to home page
                    return redirect("/")
                else:
                    return redirect("{}".format(red_req))
            else:
                error_log.append("Wrong credentials")
                return render(request , "login/login.html" , context = {"error_log" : error_log})
    else:
        try:
            request.session["username"]
        except Exception as e:
            return render(request , "login/login.html")

        else:
            return redirect("/")


def forgotcredetials(request):

    bug_hunter = []

    if request.method == "POST":
        try:
            lostuser = request.POST['email']

        except Exception as e:
            bug_hunter.append("Invalid input")
            return render(request , "login/forgot.html" , context = {"error":bug_hunter})

        else:
            try:
                userdata = Signup.objects.get(email = lostuser)
            except Signup.DoesNotExist as e:
                bug_hunter.append("Email not registered with us")
                return render(request , "login/forgot.html" , context = {"error":bug_hunter})
            else:
                if v.validate_email(lostuser):
                    hashcode = string.digits + string.ascii_letters + string.digits + string.digits
                    hashcode = "".join([random.choice(hashcode) for value in range(10)])
                    sender = "anornymous99@gmail.com"
                    receiver = lostuser
                    # message = """From: %s
                    # To: %s,
                    # Content-Type:text/html,
                    # Mime-version:1.0,
                    # Content-disposition: text,
                    # Subject:Vibes reset password is: %s,
                    # """%("devcodesv1@gmail.com",receiver , hashcode)
                    message = "Your recovery code is <strong>%s </strong><a href='devcodes.herokuapp.com/login/updatereset/'> reset link</a>"%hashcode
                    mess = MIMEMultipart("alternatives")
                    mess["From"] = "devcodesv1@gmail.com"
                    mess["To"] = receiver
                    mess["Subject"] = "Devcodes recovery code."
                    message = MIMEText( message, "html")
                    mess.attach(message)
                    try:
                        obj=sm.SMTP('smtp.gmail.com', 587)
                        obj.starttls()
                        obj.login("devcodesv1@gmail.com","admin@devcodesv1.1")
                        obj.sendmail(sender,receiver,mess.as_string())
                        obj.close()
                    except Exception as error:
                        print("Error: {}".format(error))
                        bug_hunter.append("Connection could not be established")
                        # bug_hunter.append(error)
                        return render(request , "login/forgot.html" , context = {"error":bug_hunter})

                    else:
                        Recoverdata.objects.create(uid_id = Signup.objects.get(email = receiver).uid , secret_code = hashcode)
                        print("Message sent successfully to {}".format(receiver))
                        print("Exiting the mail client program")
                        return render(request , "login/thanks.html")
                else:
                    return render(request , "login/forgot.html" , context = {"error":bug_hunter})
    else:
        return render(request , "login/forgot.html" , context = {"error":bug_hunter})


def newcr(request):
    bug_hunter = list()
    if request.method=="POST":
        newpass = make_password(request.POST["password"])
        confirmnewpass = request.POST["confirmpassword"]
        secretcode = request.POST["code"]
        try:
            recpassword  = Recoverdata.objects.get(secret_code = secretcode)
            dataobj = Signup.objects.filter(uid = recpassword.uid_id)
        except (Recoverdata.DoesNotExist,Signup.DoesNotExist) as e:
            bug_hunter.append("Incorrect information provided.")
        else:
            dataobj.update(password = newpass)
            recpassword.delete()
        return redirect("/login/")
    else:
        return render(request , "login/newcreds.html" , context = {"error":bug_hunter})

def logout(request):
    # clear the session vars
    request.session.clear()
    request.session.flush()
    request.session["loginstatus"] = False
    return redirect("/")

login/templates/login/forgot.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<meta lang="en" name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<title>DevCodes | account recovery</title>
	<link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name"favicon">
	<link rel="stylesheet" href="{% static 'login/styles.css' %}"/>
</head>

<body>
<!-- Begining of spinner -->
<div class="loader-wrapper" id="ld">
	<span class="loader"><span class="loader-inner"></span></span>
		</div>
		<!-- End of spinner -->
		<img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo">
	<div class="bon">
		<div class="bony">

	<form action="{% url 'login:forgot' %}" method="POST">

		{% csrf_token %}
		<h3>Enter recovery email</h3>



		{% for errors in error %}
		<label class="inputlabel">
			{{errors}}
		</label>
		{% endfor %}
		<input type="email" placeholder="email" name = "email" id="username" required class="input" autocomplete>

		<p>

			</p>
		<input type="submit" value="Recover" class="input">

		<div class="forgot"  id="forgot">
			<a href="{% url 'login:login' %}">
					Login instead?
			</a>
		</div>

		<p style="text-align:center">
			<span class="new">New member?</span>

			<a class="link" href="{% url 'signup:signup' %}">
				<b>Signup</b>
			</a>

		</p>
	</form>
	</div>
</div>
<script>
	 // Listen for when everything has loaded
     window.addEventListener("load", removePage, false);
        const loader = document.getElementById('ld');
        function removePage(){
          loader.classList.add('shrink');
        }
</script>
</body>
</html>

login/templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<meta lang="en" name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<title>DevCodes | Login </title>
	<link rel="stylesheet" href="{% static 'home/spinner.css' %}">
	<link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name="favicon">
	<link rel="stylesheet" href="{% static 'login/styles.css' %}"/>

</head>

<body>

<!-- Begining of spinner -->
<div class="loader-wrapper" id="ld">
	<span class="loader"><span class="loader-inner"></span></span>
		</div>
		<!-- End of spinner -->

	<div class="bon">
		<div class="prof-pic">
			<img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo" style="width: 100px;">
		</div>


		<div class="bony">

	<form action="{% url 'login:login' %}" method="POST" class="form-hander">
		{% csrf_token %}
		<h3> Login Here</h3>

		{% for error in error_log %}
		<label class="inputlabel">
			{{error}}
		</label>
		{% endfor %}
		<input type="text" placeholder="Username" name = "username" id="username" required class="input">

		<input type="password" placeholder="Password" name = "password" id="password" required class="input">
		<p>
				<div class="keepme">
					<input type="checkbox" id="keepme">
					<label for="keepme">keep me signed in</label>
				</div>

			</p>
		<input type="submit" value="login" class="input">

		<div class="forgot"  id="forgot">
			<a href="{% url 'login:forgot' %}">
					forgot password?
			</a>
		</div>

		<p style="text-align:center">
			<span class="new">New member? </span>

			<a class="link" href="{% url 'signup:signup' %}">
				Signup
			</a>

		</p>
	</form>
	</div>
</div>
<script>
	 // Listen for when everything has loaded
     window.addEventListener("load", removePage, false);
        const loader = document.getElementById('ld');
        function removePage(){
          loader.classList.add('shrink');
        }
</script>
</body>
</html>

login/templates/login/newcreds.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<meta lang="en" name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<title>DevCodes | account recovery</title>
	<link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name"favicon">
	<link rel="stylesheet" href="{% static 'login/styles.css' %}"/>
</head>

<body>
<!-- Begining of spinner -->
<div class="loader-wrapper" id="ld">
	<span class="loader"><span class="loader-inner"></span></span>
		</div>
		<!-- End of spinner -->
		<img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo">
	<div class="bon">
		<div class="bony">

	<form action="{% url 'login:newcreds' %}" method="POST">

		{% csrf_token %}
		<h3>Enter recovery email</h3>
		{% for errors in error %}
		<label class="inputlabel">
			{{errors}}
		</label>
		{% endfor %}
		<input type="password" placeholder="code" name = "code" id="username" required class="input" autocomplete>
		<input type="password" placeholder="password" name = "password" id="username" required class="input" autocomplete>
		<input type="password" placeholder="password" name = "confirmpassword" id="username" required class="input" autocomplete>

		<p>

			</p>
		<input type="submit" value="Recover" class="input">

		<div class="forgot"  id="forgot">
			<a href="{% url 'login:login' %}">
					Login instead?
			</a>
		</div>

		<p style="text-align:center">
			<span class="new">New member?</span>

			<a class="link" href="{% url 'signup:signup' %}">
				<b>Signup</b>
			</a>

		</p>
	</form>
	</div>
</div>
<script>
	 // Listen for when everything has loaded
     window.addEventListener("load", removePage, false);
        const loader = document.getElementById('ld');
        function removePage(){
          loader.classList.add('shrink');
        }
</script>
</body>
</html>

login/templates/login/recovery.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<meta lang="en" name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<title>DevCodes | recovery</title>
	<link rel="stylesheet" href="{% static 'home/spinner.css' %}">
	<link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name"favicon">
	<link rel="stylesheet" href="{% static 'login/styles.css' %}"/>
</head>

<body>

<!-- Begining of spinner -->
<div class="loader-wrapper" id="ld">
	<span class="loader"><span class="loader-inner"></span></span>
		</div>
		<!-- End of spinner -->
	<p>
		<img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo">

	</p>
	<div class="bon">
		<div class="bony">

	<form action="{% url 'login:login' %}" method="POST">
		{% csrf_token %}
		<h3> Login Here</h3>

		{% for error in error_log %}
		<label class="inputlabel">
			{{error}}
		</label>
		{% endfor %}
		<input type="text" placeholder="username" name = "username" id="username" required class="input">

		<input type="password" placeholder="password" name = "password" id="password" required class="input">
		<p>
				<div class="keepme">
					<input type="checkbox" id="keepme">
					<label for="keepme">keep me signed in</label>
				</div>

			</p>
		<input type="submit" value="login" class="input">

		<div class=""  id="forgot">
			<a href="{% url 'login:forgot' %}">
					<b>forgot password?</b>
			</a>
		</div>

		<p style="text-align:center">
			<span>New member?</span>

			<a class="link" href="{% url 'signup:signup' %}">
				<b>Signup</b>
			</a>

		</p>
	</form>
	</div>
</div>
<script>
	 // Listen for when everything has loaded
     window.addEventListener("load", removePage, false);
        const loader = document.getElementById('ld');
        function removePage(){
          loader.classList.add('shrink');
        }
</script>
</body>
</html>

login/templates/login/thanks.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<meta lang="en" name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<title>DevCodes | account recovery</title>
	<link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name"favicon">
	<link rel="stylesheet" href="{% static 'login/styles.css' %}"/>
</head>

<body>
	<p>
		<img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo">

	</p>
	<div class="bon">
		<div class="bony">
			<label class="inputlabel inputlabelmod">
				Thank you for taking your time. We've sent reset password to your account as you provided.
				Reset your password As soon as you get there. Check your spam folder if incase it's not in your inbox
			</label>


		<p style="text-align:center">
			<a href="{% url 'login:login' %}">
					<b>Login instead?</b>
			</a>

		</p>
	</div>
</div>

</body>
</html>

login/templates/login/verify.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
	<meta lang="en" name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<title>DevCodes | account Activation</title>
	<link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name"favicon">
	<link rel="icon" href="questions/images/devcodes.svg' %}" name"favicon">
</head>

<body>

<!-- Begining of spinner -->
<div class="loader-wrapper" id="ld">
	<span class="loader"><span class="loader-inner"></span></span>
		</div>
		<!-- End of spinner -->


		<img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo">

	<div class="bon">
		<div class="bony">

	<form action="{% url 'login:forgot' %}" method="POST">

		{% csrf_token %}
		<h3>Enter the Activation code</h3>



		{% for errors in error %}
		<label class="inputlabel">
			{{errors}}
		</label>
		{% endfor %}
		<input type="text" placeholder="verification code" name = "verifcode" id="username" required class="input" autocomplete>
		<!-- <p>
		</p> -->
		<input type="submit" value="Recover" class="input">

		<div class="forgot"  id="forgot">
			<a href="{% url 'login:login' %}">
					Login instead?
			</a>
		</div>

		<p style="text-align:center">
			<span class="new">New member?</span>

			<a class="link" href="{% url 'signup:signup' %}">
				<b>Signup</b>
			</a>

		</p>
	</form>
	</div>
</div>
<script>
	 // Listen for when everything has loaded
     window.addEventListener("load", removePage, false);
        const loader = document.getElementById('ld');
        function removePage(){
          loader.classList.add('shrink');
        }
</script>
</body>
</html>