home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"

urlpatterns = [
    url("^$" , views.homeview , name = "home"),
]

login/urls.py
from . import views
from django.conf.urls import url
app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
    url("^logout/" , views.logout , name = "logout"),
    url("^updatereset/" , views.newcr , name = "newcreds")
]

luckbuyer/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url,include

urlpatterns = [
    url("^$" , include("home.urls")),
    url("^login/" , include("login.urls")),
    url("^signup/$" , include("signup.urls")),
    url("^orders/" , include("orders.urls")),
    url("^stockmanager/" , include("stockmanager.urls")),
    url("^/chatroom" , include("chatroom.urls")),
    url('admin/', admin.site.urls),
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = "signup"


urlpatterns = [
    url('^$' , views.signup , name = 'signup'),
    url('^userauthentication/' , views.userauthentication , name = 'userauthentication'),
    url('^emailauthentication/' , views.emailauthentication , name = 'emailauthentication'),
]

signup/models.py
from django.db import models
from cloudinary.models import CloudinaryField
# Create your models here.
class Signup(models.Model):
    uid = models.AutoField(primary_key=True)
    email = models.EmailField(max_length = 60 , unique = True)
    username = models.CharField(max_length = 30 , unique = True)
    pnumber = models.IntegerField()
    location = models.CharField(max_length = 30  , default = "Nairobi/Kenya")
    hobby = models.CharField(max_length = 30)
    profilepic = CloudinaryField("image")
    # profilepic = models.FileField()
    password = models.CharField(max_length = 255)
    is_admin = models.BooleanField(default = False)
    # is_activated = models.BooleanField(default = False)

    class Meta:
        db_table = "signup"

signup/forms.py
from django.forms import form


# Create your forms here

signup/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
# Create your views here.
from .models import Signup as signmodel
from django.contrib.auth.hashers import make_password
import validate_email as v



def password_master(pass1,pass2):

    if pass1==pass2:
        return True

    else:
        return False


def signup(request):
    error_log = list()
    if request.method == "POST":
        username = request.POST['username']
        pnumber = request.POST['pnumber']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        hobby = request.POST['hobby'].title()
        profilepic = request.FILES['profilepic']
        # location = "Hello"
        passwordflag = password_master(pass1 , pass2)

        if passwordflag:
            password = make_password(request.POST['pass1'])
            if v.validate_email(email):
                try:
                    signmodel.objects.get(email = email)
                except Exception as e:
                    try:
                        signmodel.objects.get(username = username)

                    except Exception as e:
                        signmodel.objects.create(username = username , pnumber = pnumber , email = email , password = password ,
                        hobby = hobby , profilepic = profilepic , is_admin = False)
                        # cloudinary.uploader.upload(profilepic)
                        return redirect("/login/")

                    else:
                        error_log.append("User exists")
                        print("\n\n\n\n\n{}".format(error_log))
                        return render(request , "signup/signup.html" , context = {"error_log":error_log})

                else:
                    error_log.append("User exists")
                    print("\n\n\n\n\n{}".format(error_log))
                    return render(request , "signup/signup.html" , context = {"error_log":error_log})
            else:
                error_log.append("Email does not exists")
                return render(request , "signup/signup.html" , context = {"error_log":error_log})

        else:
            error_log.append("Password not correct")
            return render(request , "signup/signup.html" , context = {"error_log":error_log})

    else:
        return render(request , "signup/signup.html")



# username is in use?
def userauthentication(request):
    try:
        uname = request.POST['username']

    except Exception as e:
        pass

    else:
        try:
            signmodel.objects.get(username = uname)

        except Exception as e:
            return HttpResponse("false")

        else:
            return HttpResponse("true")



# email is in use?
def emailauthentication(request):
    try:
        email = request.POST['email']
    except Exception as e:
        pass

    else:
        try:
            signmodel.objects.get(email = email)
        except Exception as e:
            if v.validate_email(email):
                return HttpResponse("false")
            else:
                return HttpResponse("Email not found")

        else:
            return HttpResponse("true")

signup/templates/signup/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name="favicon">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<meta lang="en" name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'signup/styles.css' %}"/>
	<link rel="stylesheet" href="{% static 'home/spinner.css' %}">
	<title>DevCodes | signup </title>
</head>
<body>
	<!-- Begining of spinner -->
	<div class="loader-wrapper" id="ld">
		<span class="loader"><span class="loader-inner"></span></span>
			</div>
			<!-- End of spinner -->
			<div class="logoN">
				<img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo">
			</div>
	<div class="bon">
		<div class="bony">
			<form action="{% url 'signup:signup' %}" method="post" enctype="multipart/form-data" onabort="cancel()">
				<h2 class="title">Join DevCodes</h2>
					{% for error in error_log %}
					<label class="inputlabel">
						{{error}}
				</label>
					{% endfor %}
					{% csrf_token %}
				<!-- <input type="hidden" name="_token" value="{{ csrf_token }}" id="tok"> -->
				<input type="text" placeholder="Username" name = "username" required autocomplete="true" class="input" onchange="userauthentication()" id="uname">
				<label id="usernamevalid" class="validation"></label>
				<input type="phone" name="pnumber" placeholder="phone" class="input" id="phone">
				<input type="email" name="email" placeholder="email" required autocomplete="true" class="input" onchange="emailauthentication()" id="ema">
				<label id="emailvalid" class="validation"></label>
				<!-- <input type="password" name = "pass1" placeholder="Password" id="pass1" required  class="input passfield" onchange="passwordmaster(pass1)"> <i class="fa fa-eye" id="stats" aria-hidden="true" onclick="showpass();"></i>
				<label id="passwordm" class="validation"></label> -->

				<input type="password" name = "pass1" placeholder="Password" id="pass1"
		    required  class="input" onchange="passwordmaster()">
		    <label id="shortPass" class="pass">* short password * </label>

				<!-- <input type="password" placeholder="confirm password" name="pass2" id="pass2" class="input passfield" onchange="passwordmaster(pass2)" required> -->
				<input type="password" placeholder="confirm password" name="pass2" id="pass2"
		    class="input" onchange="passwordmaster()" required>
		    <label id ="mismatch" class="miss"> * password mismatch *</label>

				<input type="text" placeholder="Fav programming Language" name = "hobby" required autocomplete="true" class="input" id="hobby">
				<label id ="favlang" class="favlang"> * Programming language must be filled *</label>
				<input type="file" name="profilepic" value="Profile picture" class="input" id="profile" required>
				<!-- <input type="submit" name="submit" value="signup" id="submit" class="input" onclick="spinnermanager()"> -->
				<button type="submit" name="submit" class="btn btn-info" id="submit" onclick="form_manager()" onabort="cancel()">
					Signup
					<!-- <i class="" id="submit"></i> -->
					<i class="" id="spin"></i>
				</button>
			</form>
				<p style="text-align:center">
					<span class="title">Already have an account?</span>
						<a class="link" href="{% url 'login:login' %}">
						Sign in
					</a>
				</p>
	</div>
</div>
	<script src="{% static 'signup/devcodes.js' %}" charset="utf-8"></script>
	<script type="text/javascript">

	function userauthentication(){
		var xhttp = new XMLHttpRequest();
		var user = document.getElementById("uname").value;
		xhttp.onreadystatechange = function()
		{
			if(this.readyState == 4 && this.status == 200)
			{
				if(this.responseText == "true")
					{
						document.getElementById("usernamevalid").innerHTML = "username taken";
						document.getElementById("usernamevalid").style.color = "#f00";
						// document.getElementById("submit").disabled=true;
					}

					else {
						document.getElementById("usernamevalid").innerHTML = "username available";
						document.getElementById("usernamevalid").style.color = "#7fa";
						// document.getElementById("submit").enabled=true;
					}
			}
		}
		xhttp.open("POST" , "{% url 'signup:userauthentication' %}" , true);
		xhttp.setRequestHeader("Content-Type" , "application/x-www-form-urlencoded");
		xhttp.setRequestHeader("X-CSRFToken" , "{{csrf_token}}");
		xhttp.send("username="+user);
	}

		function emailauthentication(){
			var xhttp = new XMLHttpRequest();
			var email = document.getElementById("ema").value;
			xhttp.onreadystatechange = function(){
				if(this.readyState == 4 && this.status == 200)
				{
					if(this.responseText == "true")
					{
						document.getElementById("emailvalid").innerHTML = "Email in use by another account";
						document.getElementById("emailvalid").style.color = "#f00";
						// document.getElementById("submit").disabled=true;
					}

					else if(this.responseText == "false"){
						document.getElementById("emailvalid").innerHTML = "email available";
						document.getElementById("emailvalid").style.color = "#7fa";
						// document.getElementById("submit").enabled=true;
					}
					else{
						document.getElementById("emailvalid").innerHTML = this.responseText;
						document.getElementById("emailvalid").style.color = "#f00f00";
					}
				}
			}
			xhttp.open("POST" , "{% url 'signup:emailauthentication' %}" , true);
			xhttp.setRequestHeader("Content-Type" , "application/x-www-form-urlencoded");
			xhttp.setRequestHeader("X-CSRFToken" , "{{csrf_token}}");
			xhttp.send("email="+email);
		}
	</script>
</body>
</html>